name: Ckb4ibc
on:
  pull_request:
    path:
      - .github/workflows/ckb4ibc-test.yaml
      - Cargo.toml
      - Cargo.lock
      - ci/**
      - crates/**
      - tools/**
  push:
    branches: main
      - .github/workflows/ckb4ibc-test.yaml
      - Cargo.toml
      - Cargo.lock
      - ci/**
      - crates/**
      - tools/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  integration-test:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: add test key
        run: |
          mkdir -p ~/.hermes/keys/ckb4ibc-0/keyring-test
          mkdir -p ~/.hermes/keys/ckb4ibc-1/keyring-test
          cp ./tools/forcerelay-test/ckb/relayer_ckb_wallet.json ~/.hermes/keys/ckb4ibc-0/keyring-test
          cp ./tools/forcerelay-test/ckb/relayer_ckb_wallet.json ~/.hermes/keys/ckb4ibc-1/keyring-test
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p ibc-relayer
      - name: prepare-ckb
        run: |
          if [ ! -f "/tmp/ckb.tar.gz" ]; then
            curl -L https://github.com/nervosnetwork/ckb/releases/download/v0.107.0/ckb_v0.107.0_x86_64-unknown-linux-gnu.tar.gz -o /tmp/ckb.tar.gz
          fi
          tar -zxf /tmp/ckb.tar.gz -C /tmp
          echo "/tmp/ckb_v0.107.0_x86_64-unknown-linux-gnu" >> $GITHUB_PATH
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p ckb4ibc-test --lib --all-features -- tests::integration_test --exact --nocapture --ignored
